---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbook_path: site-cookbooks/

platforms:
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[ruby::default]
    attributes:
