---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbook_path: my-cookbooks/apache

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[zsh::default]
      - recipe[apache::default]
    attributes:
