version: 0.1

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip && unzip -d /usr/local/bin/ packer_0.12.2_linux_amd64.zip
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - packer version
      - packer build packer/test_ami.json
  post_build:
    commands:
      - echo Build completed on `date`
