version: 0.1

environment_variables:
  plaintext:
    PACKER_VERSION: "1.0.2"

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/packer/"$PACKER_VERSION"/packer_"$PACKER_VERSION"_linux_amd64.zip && unzip -d /usr/local/bin/ packer_"$PACKER_VERSION"_linux_amd64.zip
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws ec2 describe-instances
      - packer version
      - packer build packer/test_ami.json
      - ls -la /bin/sh
      - which sh
  post_build:
    commands:
      - echo Build completed on `date`
